#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V 
bspc monitor HDMI1 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20
bspc config top_padding         20
bspc config bottom_padding      20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

feh --bg-scale Downloads/bg-space-ff5065.jpg
picom --config .config/picom.conf --shadow-exclude 'focused'
