#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V 
bspc monitor HDMI1 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20
bspc config top_padding         20
bspc config bottom_padding      20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --output HDMI-1 --mode 1920x1080 --pos 1920x0
feh --bg-scale Downloads/bg-space-ff5065.jpg
picom --config .config/picom.conf --shadow-exclude 'focused'
$HOME/.config/polybar/launch.sh
# picom --config .config/picom.conf --active-shadow-red '1' --active-shadow-green '1' --active-shadow-blue '1'
